---
# This playbook sets up backup for the server.
# pass the host and user as extra variables.

- hosts: $host
  user: $user
  sudo: yes
  vars:
    venv_path: "/opt/aws_venv/"
  vars_files:
  - vars/credentials_${host}.yml
  tasks:

  - name: create backup mysql user
    mysql_user: name=$backup_db_user password=$backup_db_password priv="*.*:SELECT,LOCK TABLES" state=present

  - name: Install required software packages
    apt: pkg=$item state=installed
    with_items:
    - python-setuptools

  - name: install pip and virtuan env
    easy_install: name=$item
    with_items:
    - pip
    - virtualenv

  - name: create python virtual environment
    command: /usr/bin/env virtualenv --system-site-packages $venv_path

  - name: install virtual environment packages
    pip: name=$item virtualenv=$venv_path
    with_items:
    - boto
    - filechunkio

  - name: Check out backup rotation code
    git: repo=https://github.com/dirkcuys/active-memory.git dest=/opt/active-memory

  - name: Create backup directory for mysql
    file: path=/opt/backup/mysql state=directory

  - name: Create backup directory for media
    file: path=/opt/backup/media state=directory

  - name: Copy mysql backup script to server
    copy: src=files/backup-mysql.sh dest=/opt/backup/backup-mysql.sh
        
  - name: Copy media backup script to server
    copy: src=files/backup-media.sh dest=/opt/backup/backup-media.sh
        
  - name: Copy backup credentials to server
    template: src=templates/etc_backup-credentials.sh.j2 dest=/etc/backup-credentials.sh mode=0750 owner=root group=backup

  - name: Add cron entry to run backup-mysql script daily at 11h00 UTC
    cron: name="backup-mysql" hour="3" minute="0" job="/opt/backup/backup-mysql.sh" state=present

  - name: Add cron entry to run backup-media script daily at 12h00 UTC
    cron: name="backup-media" hour="4" minute="0" job="/opt/backup/backup-media.sh" state=present
