---
- name: create postgres user
  postgresql_user:
    name: "{{LEARNINGCIRCLES.DB_USER}}"
    password: "{{LEARNINGCIRCLES.DB_PASSWORD}}"
    login_host: "127.0.0.1"
    login_user: "{{PG_ADMIN_USER}}"
    login_password: "{{PG_ADMIN_PASSWORD}}"

- name: create postgres db
  postgresql_db:
    name: "{{LEARNINGCIRCLES.DB_NAME}}"
    encoding: UTF-8
    login_host: "127.0.0.1"
    login_user: "{{PG_ADMIN_USER}}"
    login_password: "{{PG_ADMIN_PASSWORD}}"
    owner: "{{LEARNINGCIRCLES.DB_USER}}"

- name: setup static and media file hosting through nginx-proxy
  template: src=static.j2 dest=/var/p2pu/volumes/p2pu-nginx/vhosts.d/{{LEARNINGCIRCLES.DOMAIN}}

# Doing this before restarting the containers, keeps the currently running image + container
- name: Remove old docker images & containers
  docker_prune:
    images: yes
    containers: yes
    builder_cache: yes

# Setup env variables for sharing between django containers and celery containers. They need basically the same ENV variables except for the Nginx specific ones.
- set_fact:
    lc_nginx_env:
      VIRTUAL_HOST: "{{LEARNINGCIRCLES.DOMAIN}}"
      LETSENCRYPT_HOST: "{{LEARNINGCIRCLES.DOMAIN}}"
      LETSENCRYPT_EMAIL: "admin@p2pu.org"

- set_fact: 
    lc_app_env: "{{ lc_docker_env | combine(lc_nginx_env) }}"

- name: start docker container for django
  docker_container:
    name: "{{LEARNINGCIRCLES.DOMAIN}}"
    image: "p2pu/learning-circles:{{LEARNINGCIRCLES.BRANCH}}"
    state: started
    pull: yes
    recreate: true
    restart: yes
    restart_policy: always
    volumes:
    - "/var/p2pu/volumes/p2pu-nginx/static/{{LEARNINGCIRCLES.DOMAIN}}/static:/opt/app/static_serve"
    - "/var/p2pu/volumes/p2pu-nginx/static/{{LEARNINGCIRCLES.DOMAIN}}/media:/opt/app/upload"
    - "/var/p2pu/volumes/{{LEARNINGCIRCLES.DOMAIN}}/celery:/var/lib/celery"
    - "/var/p2pu/volumes/{{LEARNINGCIRCLES.DOMAIN}}/log:/var/log"
    links:
    - "p2pu-postgres:postgres"
    - "{{RABBITMQ_HOSTNAME}}:rabbitmq"
    env: "{{lc_app_env}}"
    log_driver: fluentd
    log_options:
        tag: django


- name: start docker container for celery
  docker_container:
    name: "{{LEARNINGCIRCLES.DOMAIN}}-celery"
    image: "p2pu/learning-circles:{{LEARNINGCIRCLES.BRANCH}}"
    state: started
    pull: yes
    user: celery
    recreate: true
    restart: yes
    restart_policy: always
    volumes:
    - "/var/p2pu/volumes/p2pu-nginx/static/{{LEARNINGCIRCLES.DOMAIN}}/static:/opt/app/static_serve"
    - "/var/p2pu/volumes/p2pu-nginx/static/{{LEARNINGCIRCLES.DOMAIN}}/media:/opt/app/upload"
    - "/var/p2pu/volumes/{{LEARNINGCIRCLES.DOMAIN}}/celery:/var/lib/celery"
    - "/var/p2pu/volumes/{{LEARNINGCIRCLES.DOMAIN}}/log:/var/log"
    links:
    - "p2pu-postgres:postgres"
    - "{{RABBITMQ_HOSTNAME}}:rabbitmq"
    command: /opt/django-venv/bin/celery worker -A learnwithpeople --loglevel=INFO 
    env: "{{lc_docker_env}}"
    log_driver: fluentd
    log_options:
        tag: celery


- name: start docker container for celery beat
  docker_container:
    name: "{{LEARNINGCIRCLES.DOMAIN}}-celerybeat"
    image: "p2pu/learning-circles:{{LEARNINGCIRCLES.BRANCH}}"
    state: started
    pull: yes
    user: celery
    recreate: true
    restart: yes
    restart_policy: always
    volumes:
    - "/var/p2pu/volumes/p2pu-nginx/static/{{LEARNINGCIRCLES.DOMAIN}}/static:/opt/app/static_serve"
    - "/var/p2pu/volumes/p2pu-nginx/static/{{LEARNINGCIRCLES.DOMAIN}}/media:/opt/app/upload"
    - "/var/p2pu/volumes/{{LEARNINGCIRCLES.DOMAIN}}/celery:/var/lib/celery"
    - "/var/p2pu/volumes/{{LEARNINGCIRCLES.DOMAIN}}/log:/var/log"
    links:
    - "p2pu-postgres:postgres"
    - "{{RABBITMQ_HOSTNAME}}:rabbitmq"
    command: /opt/django-venv/bin/celery beat -A learnwithpeople --loglevel=DEBUG --pidfile=/var/lib/celery/celerybeat.pid --schedule=/var/lib/celery/celerybeat-schedule 
    env: "{{lc_docker_env}}"
    log_driver: fluentd
    log_options:
        tag: celery-beat
