---
# This playbook sets up backup for the server.
# pass the host and user as extra variables.

- hosts: $host
  user: $user
  sudo: yes
  vars:
    venv_path: "/opt/aws_venv/"
  vars_files:
  - vars/credentials_${host}.yml
  tasks:

  - name: Install required software packages
    apt: pkg=$item state=installed
    with_items:
    - python-setuptools

  - name: install pip and virtuan env
    easy_install: name=$item
    with_items:
    - pip
    - virtualenv

  - name: create python virtual environment
    command: /usr/bin/env virtualenv --system-site-packages $venv_path

  - name: install virtual environment packages
    pip: name=$item virtualenv=$venv_path
    with_items:
    - boto
    - filechunkio

  - name: Check out backup rotation code
    git: repo=https://github.com/dirkcuys/active-memory.git dest=/opt/active-memory

  - name: Create backup directory for postgresql
    file: path=/opt/backup/postgresql state=directory

  - name: Create backup directory for uploads
    file: path=/opt/backup/uploads state=directory

  - name: Copy postgresql backup script to server
    copy: src=files/backup-postgresql.sh dest=/opt/backup/backup-postgresql.sh mode=0755
        
  - name: Copy upload backup script to server
    copy: src=files/backup-uploads.sh dest=/opt/backup/backup-uploads.sh mode=0755
        
  - name: Copy backup credentials to server
    template: src=templates/etc_backup-credentials.sh.j2 dest=/etc/backup-credentials.sh mode=0640 owner=root group=backup

  - name: Add cron entry to run backup-postgresql script daily at 9h30 UTC
    cron: name="backup-postgresql" hour="9" minute="30" job="/opt/backup/backup-postgresql.sh" state=present

  - name: Add cron entry to run backup-uploads script daily at 10h30 UTC
    cron: name="backup-uploads" hour="10" minute="30" job="/opt/backup/backup-uploads.sh" state=present
