---
- name: etherpad
  hosts: etherpad
  become: yes
  become_method: sudo
  tags:
  - etherpad
  vars_files:
    - vars/etherpad.yml
  vars:
    POSTGRES_CONTAINER: p2pu-postgres 
  roles:
  - common
  - angstwad.docker_ubuntu
  - nginx-proxy
  - postgres
  - role: postgres_role
    vars:
      DB_NAME: "{{ETHERPAD_DB_NAME}}"
      DB_USER: "{{ETHERPAD_DB_USER}}"
      DB_PASSWORD: "{{ETHERPAD_DB_PASSWORD}}"
  - etherpad
