---
- name: learningcircles
  hosts: learningcircles
  become: yes
  become_method: sudo
  tags:
  - learningcircles
  vars_files:
    - vars/learningcircles.yml
  roles:
  - common
  - docker_ubuntu
  - monitor
  - fluentd
  - nginx-proxy
  - postgres
  - rabbitmq
  - learningcircles-app
  - p2pu-redirect
  - howto-redirect
