# This role install a rabbitmq server

---
- name: RabbitMQ docker container
  docker_container:
    docker_api_version: 1.22
    name: "{{RABBITMQ_HOSTNAME}}"
    hostname: "{{RABBITMQ_HOSTNAME}}"
    image: rabbitmq:3
    pull: yes
    state: started
    restart: yes
    restart_policy: always
    volumes:
    - "/var/p2pu/volumes/{{RABBITMQ_HOSTNAME}}:/var/lib/rabbitmq"
    env:
      RABBITMQ_NODENAME: "{{RABBITMQ_HOSTNAME}}"
