# This role install a rabbitmq server

---
- name: RabbitMQ docker container
  docker:
    docker_api_version: 1.22
    name: "{{RABBITMQ_HOSTNAME}}"
    hostname: "{{RABBITMQ_HOSTNAME}}"
    image: rabbitmq:3
    pull: always
    state: reloaded
    restart_policy: always
    volumes:
    - "/var/p2pu/volumes/{{RABBITMQ_HOSTNAME}}:/var/lib/rabbitmq"
    env:
      RABBITMQ_NODENAME: "{{RABBITMQ_HOSTNAME}}"
