---
- name: learningcircles
  hosts: learningcircles
  become: yes
  become_method: sudo
  tags:
  - production
  vars_files:
    - vars/learningcircles.yml
  roles:
  - common
  - angstwad.docker_ubuntu
  - nginx-proxy
  - postgres
  - rabbitmq
  - learningcircles-app

- name: staging-learningcircles
  hosts: staging-learningcircles
  become: yes
  become_method: sudo
  tags: 
  - staging
  vars_files:
  - vars/staging-learningcircles.yml
  roles:
  - common
  - angstwad.docker_ubuntu
  - nginx-proxy
  - postgres
  - rabbitmq
  - learningcircles-app
