---
- name: install git
  apt: pkg=git-core state=installed

- name: get Dockerfile
  git: repo=https://github.com/p2pu/docker-images.git dest=/var/docker-images

- name: build docker image
  docker_image: path="/var/docker-images/knight-container" name="p2pu/knight-app" state=build

- name: create postgres user
  postgresql_user:
    name: "{{KNIGHT.DB_USER}}"
    password: "{{KNIGHT.DB_PASSWORD}}"
    login_host: "127.0.0.1"
    login_user: "{{PG_ADMIN_USER}}"
    login_password: "{{PG_ADMIN_PASSWORD}}"


- name: create postgres db
  postgresql_db:
    name: "{{KNIGHT.DB_NAME}}"
    encoding: UTF-8
    login_host: "127.0.0.1"
    login_user: "{{PG_ADMIN_USER}}"
    login_password: "{{PG_ADMIN_PASSWORD}}"
    owner: "{{KNIGHT.DB_USER}}"


- name: setup static and media file hosting through nginx-proxy
  template: src=static.j2 dest=/var/p2pu/volumes/p2pu-nginx/vhosts.d/{{KNIGHT.DOMAIN}}

- name: start docker container
  docker:
    name: p2pu-knight
    image: p2pu/knight-app:latest
    state: reloaded
    restart_policy: always
    volumes:
    - "/var/p2pu/volumes/p2pu-nginx/static/{{KNIGHT.DOMAIN}}/static:/var/app/static_serve"
    - "/var/p2pu/volumes/p2pu-nginx/static/{{KNIGHT.DOMAIN}}/media:/var/app/upload"
    - "/var/p2pu/volumes/knight/celery:/var/lib/celery"
    links:
    - "p2pu-postgres:postgres"
    - "knight-rabbitmq:rabbitmq"
    env:
      VIRTUAL_HOST: "{{KNIGHT.DOMAIN}}"
      DOMAIN: "{{KNIGHT.DOMAIN}}"
      DATABASE_URL: "postgres://{{ KNIGHT.DB_USER }}:{{ KNIGHT.DB_PASSWORD }}@postgres:5432/{{KNIGHT.DB_NAME}}"
      ADMIN_EMAIL: "{{KNIGHT.ADMIN_EMAIL}}"
      SECRET_KEY: "{{KNIGHT.SECRET_KEY}}"
      EMAIL_HOST: "{{KNIGHT.EMAIL_HOST}}"
      EMAIL_HOST_USER: "{{KNIGHT.EMAIL_HOST_USER}}"
      EMAIL_HOST_PASSWORD: "{{KNIGHT.EMAIL_HOST_PASSWORD}}"
      DEFAULT_FROM_EMAIL: "{{KNIGHT.DEFAULT_FROM_EMAIL}}"
      AWS_ACCESS_KEY_ID: "{{KNIGHT.AWS_ACCESS_KEY_ID}}"
      AWS_SECRET_ACCESS_KEY: "{{KNIGHT.AWS_SECRET_ACCESS_KEY}}"
      AWS_STORAGE_BUCKET_NAME: "{{KNIGHT.AWS_STORAGE_BUCKET_NAME}}"
      TWILIO_ACCOUNT_SID: "{{KNIGHT.TWILIO_ACCOUNT_SID}}"
      TWILIO_AUTH_TOKEN: "{{KNIGHT.TWILIO_AUTH_TOKEN}}"
      TWILIO_NUMBER: "{{KNIGHT.TWILIO_NUMBER}}"
      BROKER_URL: "amqp://guest:guest@rabbitmq//"
