---
# TODO consider using docker images from docker hub
- name: install git
  apt: pkg=git-core state=installed

- name: get application code
  git: 
    repo: "https://github.com/p2pu/learning-circles.git"
    dest: "/usr/src/learningcircles"
    version: "{{LEARNINGCIRCLES.BRANCH}}"

- name: build docker image
  command: docker build -t "p2pu/learningcircles:{{LEARNINGCIRCLES.BRANCH}}" /usr/src/learningcircles

- name: create postgres user
  postgresql_user:
    name: "{{LEARNINGCIRCLES.DB_USER}}"
    password: "{{LEARNINGCIRCLES.DB_PASSWORD}}"
    login_host: "127.0.0.1"
    login_user: "{{PG_ADMIN_USER}}"
    login_password: "{{PG_ADMIN_PASSWORD}}"

- name: create postgres db
  postgresql_db:
    name: "{{LEARNINGCIRCLES.DB_NAME}}"
    encoding: UTF-8
    login_host: "127.0.0.1"
    login_user: "{{PG_ADMIN_USER}}"
    login_password: "{{PG_ADMIN_PASSWORD}}"
    owner: "{{LEARNINGCIRCLES.DB_USER}}"

- name: setup static and media file hosting through nginx-proxy
  template: src=static.j2 dest=/var/p2pu/volumes/p2pu-nginx/vhosts.d/{{LEARNINGCIRCLES.DOMAIN}}

- name: start docker container
  docker:
    docker_api_version: 1.22
    name: "{{LEARNINGCIRCLES.DOMAIN}}"
    image: "p2pu/learningcircles:{{LEARNINGCIRCLES.BRANCH}}"
    state: reloaded
    restart_policy: always
    volumes:
    - "/var/p2pu/volumes/p2pu-nginx/static/{{LEARNINGCIRCLES.DOMAIN}}/static:/var/app/static_serve"
    - "/var/p2pu/volumes/p2pu-nginx/static/{{LEARNINGCIRCLES.DOMAIN}}/media:/var/app/upload"
    - "/var/p2pu/volumes/{{LEARNINGCIRCLES.DOMAIN}}/celery:/var/lib/celery"
    - "/var/p2pu/volumes/{{LEARNINGCIRCLES.DOMAIN}}/log:/var/log"
    links:
    - "p2pu-postgres:postgres"
    - "{{RABBITMQ_HOSTNAME}}:rabbitmq"
    env:
      VIRTUAL_HOST: "{{LEARNINGCIRCLES.DOMAIN}}"
      DOMAIN: "{{LEARNINGCIRCLES.DOMAIN}}"
      DATABASE_URL: "postgres://{{ LEARNINGCIRCLES.DB_USER }}:{{ LEARNINGCIRCLES.DB_PASSWORD }}@postgres:5432/{{LEARNINGCIRCLES.DB_NAME}}"
      ADMIN_EMAIL: "{{LEARNINGCIRCLES.ADMIN_EMAIL}}"
      SECRET_KEY: "{{LEARNINGCIRCLES.SECRET_KEY}}"
      EMAIL_HOST: "{{LEARNINGCIRCLES.EMAIL_HOST}}"
      EMAIL_HOST_USER: "{{LEARNINGCIRCLES.EMAIL_HOST_USER}}"
      EMAIL_HOST_PASSWORD: "{{LEARNINGCIRCLES.EMAIL_HOST_PASSWORD}}"
      DEFAULT_FROM_EMAIL: "{{LEARNINGCIRCLES.DEFAULT_FROM_EMAIL}}"
      TWILIO_ACCOUNT_SID: "{{LEARNINGCIRCLES.TWILIO_ACCOUNT_SID}}"
      TWILIO_AUTH_TOKEN: "{{LEARNINGCIRCLES.TWILIO_AUTH_TOKEN}}"
      TWILIO_NUMBER: "{{LEARNINGCIRCLES.TWILIO_NUMBER}}"
      BROKER_URL: "amqp://guest:guest@rabbitmq//"
      BACKUP_DIR: "{{LEARNINGCIRCLES.BACKUP_DIR}}"
      BACKUP_AWS_ACCESS_KEY_ID: "{{LEARNINGCIRCLES.BACKUP_AWS_ACCESS_KEY_ID}}"
      BACKUP_AWS_SECRET_ACCESS_KEY: "{{LEARNINGCIRCLES.BACKUP_AWS_SECRET_ACCESS_KEY}}"
      BACKUP_AWS_STORAGE_BUCKET_NAME: "{{LEARNINGCIRCLES.BACKUP_AWS_STORAGE_BUCKET_NAME}}"
      BACKUP_AWS_KEY_PREFIX: "{{LEARNINGCIRCLES.BACKUP_AWS_KEY_PREFIX}}"
      GA_TRACKING_ID: "{{LEARNINGCIRCLES.GA_TRACKING_ID}}"

