lc_docker_env:
  DOMAIN: "{{LERNANTA.DOMAIN}}"
  ADMIN_USER: "{LERNANTA.ADMIN_USER}}"
  ADMIN_EMAIL: "{{LERNANTA.ADMIN_EMAIL}}"
  SECRET_KEY: "{{LERNANTA.SECRET_KEY}}"
  EMAIL_HOST: "{{LERNANTA.EMAIL_HOST}}"
  EMAIL_HOST_USER: "{{LERNANTA.EMAIL_HOST_USER}}"
  EMAIL_HOST_PASSWORD: "{{LERNANTA.EMAIL_HOST_PASSWORD}}"
  DEFAULT_FROM_EMAIL: "{{LERNANTA.DEFAULT_FROM_EMAIL}}"
  DB_NAME: "{{LERNANTA.DB_NAME}}"
  DB_USER: "{{LERNANTA.DB_USER}}"
  DB_PASSWORD: "{{LERNANTA.DB_PASSWORD}}"
  DB_HOST: "mysql"
  RECAPTCHA_PUBLIC_KEY: "{{LERNANTA.RECAPTCHA_PUBLIC_KEY}}"
  RECAPTCHA_PRIVATE_KEY: "{{LERNANTA.RECAPTCHA_PRIVATE_KEY}}"
  EMBEDLY_KEY: "{{LERNANTA.EMBEDLY_KEY}}"
  DISQUS_SHORTNAME: "{{LERNANTA.DISQUS_SHORTNAME}}"
  DISQUS_SECRET_KEY: "{{LERNANTA.DISQUS_SECRET_KEY}}"
  DISQUS_PUBLIC_KEY: "{{LERNANTA.DISQUS_PUBLIC_KEY}}"
  BROKER_URL: "amqp://guest:guest@rabbitmq//"
  SMTP_PASSWORD: "{{LERNANTA.SMTP_PASSWORD}}"
  HELP_API_KEY: "{{LERNANTA.HELP_API_KEY}}"
