---
- name: create dir for etherpad
  file: path=/var/docker-volumes/etherpad state=directory

# uh_etherpad_session_key
- name: create session key
  copy:
    dest: /var/docker-volumes/etherpad/SESSIONKEY.txt
    content: "{{ETHERPAD_SESSION_KEY}}"
    mode: "640"
    owner: 5001

# uh_etherpad_api_key
- name: create api key
  copy:
    dest: /var/docker-volumes/etherpad/APIKEY.txt
    content: "{{ETHERPAD_API_KEY}}"
    mode: "640"
    owner: 5001

- name: clone etherpad repo
  git:
    repo: https://github.com/ether/etherpad-lite.git
    dest: /usr/local/src/etherpad
    version: "1.8.4"

- name: Build docker iamge
  docker_image:
    name: p2pu/etherpad
    build:
      path: /usr/local/src/etherpad
      pull: yes
      args: 
        ETHERPAD_PLUGINS: "ep_headings2 ep_font_size"
    tag: latest
    source: build
    force_source: yes
    state: present

- name: start docker container
  docker_container:
    name: "{{ETHERPAD_DOMAIN}}"
    image: "p2pu/etherpad"
    state: started
    pull: no
    restart: yes
    restart_policy: always
    links:
    - "{{POSTGRES_CONTAINER}}:postgres"
    volumes:
    - /var/docker-volumes/etherpad/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
    - /var/docker-volumes/etherpad/SESSIONKEY.txt:/opt/etherpad-lite/SESSIONKEY.txt
    env:
      VIRTUAL_HOST: "{{ETHERPAD_DOMAIN}}"
      LETSENCRYPT_HOST: "{{ETHERPAD_DOMAIN}}"
      LETSENCRYPT_EMAIL: "{{LETSENCRYPT_EMAIL}}"
      DOMAIN: "{{ETHERPAD_DOMAIN}}"
      ETHERPAD_TITLE: "{{ETHERPAD_TITLE}}"
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_NAME: "{{ETHERPAD_DB_NAME}}"
      DB_USER: "{{ETHERPAD_DB_USER}}"
      DB_PASS: "{{ETHERPAD_DB_PASSWORD}}"
      ADMIN_PASSWORD: "{{ETHERPAD_ADMIN_PASSWORD}}"
