---
# This playbook sets up mysql backups for the server.
# pass the host and user as extra variables.

  - name: Install required software packages
    apt: pkg={{item}} state=installed
    with_items:
    - python-setuptools

  - name: install pip and virtuan env
    easy_install: name={{item}}
    with_items:
    - pip
    - virtualenv

  - name: create python virtual environment
    command: /usr/bin/env virtualenv --system-site-packages {{venv_path}}

  - name: install virtual environment packages
    pip: name={{item}} virtualenv={{venv_path}}
    with_items:
    - dcu.active-memory

  - name: Create backup directory for postgresql
    file: path=/opt/backup/postgresql state=directory

  - name: Copy postgresql backup script to server
    copy: src=backup-postgresql.sh dest=/opt/backup/backup-postgresql.sh mode=0755
      
  - name: Copy backup credentials to server
    template: src=etc_pgbackup-credentials.sh.j2 dest=/etc/pgbackup-credentials.sh mode=0640 owner=root group=backup

  - name: Add cron entry to run backup-postgresql script daily at 9h30 UTC
    cron: name="backup-postgresql" hour="9" minute="30" job="/opt/backup/backup-postgresql.sh" state=present
