---
- name: install python-pycurl
  apt: pkg=python-pycurl state=present

- name: Install ntp
  apt: pkg=ntp state=present
  tags: ntp

- name: Ensure ntpd is running and enabled
  service: name=ntp state=started enabled=yes
  tags: ntp


