---
- name: install packages
  apt: pkg={{ item }} state=installed
  with_items:
    - php5
    - php5-mysql
    - php5-curl
    - php5-cgi
    - php5-gd
    - php5-fpm
  notify:
  - restart fpm

- name: configure FPM to use a socket rather than a port
  copy: src=www.conf dest=/etc/php5/fpm/pool.d/www.conf
  notify:
  - restart fpm
